### ISSUE TITLE
"Destroy" Shops while removing item under plate

### ISSUE THREAD

**Issue by lippoliv** [kellerkindt/ShowCaseStandalone#8]
1. Place a fence
1. Place a pressure plate on it
1. Create a shop there
1. Try to "break" the pressure plate (doesn't work, protected)
1. Try to "break" the fence... *works*

Now your Shop is broken. Short Video here: https://youtu.be/eRmHD4zFGJ4

Two Questions:
1. What can be done to discard this behavior
1. How can I repair that broken Shops?

Regarding the second: I found the regarding file in `yaml-storage` Folder. I changed the Location there, so I had a new shop. But How can I remove the Label and the item?

**Comment by lippoliv** [comment]
@tallbyte nice, thanks. Will that remove the item too?

**Comment by kellerkindt** [comment]
@lippoliv No, but you are now able to 'restore' the shop by placing a new block at its actual location
